### ISSUE TITLE
BuilderConfig 'allenai--c4' not found. Available: ['default']

### ISSUE THREAD

**Issue by MingjunHu** [DjangoPeng/LLM-quickstart#6]
AutoGPTQ_transformers   家庭作业

执行 这个的时候：
quant_model67 = AutoModelForCausalLM.from_pretrained(model_id67, quantization_config=quantization_config67, device_map='auto')

报这个错误：

BuilderConfig 'allenai--c4' not found. Available: ['default']

/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-17ac6e9393cf>](https://localhost:8080/#) in <cell line: 2>()
      1 tokenizer67 = AutoTokenizer.from_pretrained(model_id67)
----> 2 quant_model67 = AutoModelForCausalLM.from_pretrained(model_id67, quantization_config=quantization_config67, device_map='auto')

9 frames
[/usr/local/lib/python3.10/dist-packages/datasets/builder.py](https://localhost:8080/#) in _create_builder_config(self, config_name, custom_features, **config_kwargs)
    588             builder_config = self.builder_configs.get(config_name)
    589             if builder_config is None and self.BUILDER_CONFIGS:
--> 590                 raise ValueError(
    591                     f"BuilderConfig '{config_name}' not found. Available: {list(self.builder_configs.keys())}"
    592                 )

ValueError: BuilderConfig 'allenai--c4' not found. Available: ['default']

**Comment by sycao5** [comment]
I see the same error. [https://github.com/DjangoPeng/LLM-quickstart/blob/main/transformers/AutoGPTQ_transformers.ipynb）](https://github.com/DjangoPeng/LLM-quickstart/blob/main/transformers/AutoGPTQ_transformers.ipynb%EF%BC%89

```
ValueError                                Traceback (most recent call last)
[<ipython-input-6-da8f2d30e6b0>](https://localhost:8080/#) in <cell line: 2>()
      1 tokenizer = AutoTokenizer.from_pretrained(model_id)
----> 2 quant_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=quantization_config, device_map='auto')

9 frames
[/usr/local/lib/python3.10/dist-packages/datasets/builder.py](https://localhost:8080/#) in _create_builder_config(self, config_name, custom_features, **config_kwargs)
    588             builder_config = self.builder_configs.get(config_name)
    589             if builder_config is None and self.BUILDER_CONFIGS:
--> 590                 raise ValueError(
    591                     f"BuilderConfig '{config_name}' not found. Available: {list(self.builder_configs.keys())}"
    592                 )

ValueError: BuilderConfig 'allenai--c4' not found. Available: ['default']
```

**Comment by sycao5** [comment]
把数据集换成pt 之后可以跑，google 数据集c4 量化的时候有allenai--c4的问题

**Comment by MingjunHu** [comment]
@sycao5 是用dataset=‘pt’吗？
能把 config的完整配置发一下吗？

**Comment by MingjunHu** [comment]
看到了 huggingface上用的 是ptb
设置成dataset='ptb',  我也可以了
只是显存占用比较大峰值到22G了 

![image](https://github.com/DjangoPeng/LLM-quickstart/assets/9472965/b8bbfcc8-06d1-4114-bb6c-f5956f85f343)
https://huggingface.co/docs/transformers/v4.36.1/en/main_classes/quantization#transformers.GPTQConfig.dataset

**Comment by QingtaoLi1** [comment]
https://huggingface.co/datasets/allenai/c4/discussions/7 This works.
